### ISSUE TITLE
Does not work with Magento 2.4

### ISSUE THREAD

**Issue by dev-jq** [extdn/extension-dashboard-m2#5]
Installed via Composer on Magento 2.4.3-p1. After running and compiling:
an Exception error is shown instead of the module list on Extension Dashboard page.

**Comment by jissereitsma** [comment]
Thanks for reporting this. Apparently, Magento 2.4.X added specific behaviour to UiComponent grids in the backend, that assumed a data provider to always be attached to a database. In this case, the dashboard receives data from elsewhere, instead of the database. Commit https://github.com/extdn/extension-dashboard-m2/commit/22afc1cb82f58426dd6a2c65e211c800ef18c190 should fix this. Could you upgrade to see if this works for you too?

**Comment by dev-jq** [comment]
Now works fine!
Thanks :)

![dashboard-modules](https://user-images.githubusercontent.com/13614691/159686893-d56cd10a-9a65-45fc-9d6c-b80be1e6999c.png)
